spring:
    datasource:
        url: jdbc:mysql://awseb-e-a75pprycuv-stack-awsebrdsdatabase-mxpafsrmwbxo.clmsuvt265ah.ap-northeast-2.rds.amazonaws.com/board?useSSL=false&serverTimezone=UTC
        username: fastcam
        password: 00000000a
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
